baseurl = "https://github.com/mikhaylo1/beautifulhugo"
DefaultContentLanguage = "en"
title = "DeskCamera"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "DeskCamera" # Set a different text for the header on the home page
  subtitle = "Virtual ONVIF & RTSP Camera for Recording PC Screen to VMS"
  mainSections = ["post","posts"]
  logo = "img/deskcamera-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = false
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "DeskCamera"
  website = "https://www.blog.deskcamera.com"
  email = "sales@deskcamera.com"
  facebook = "https://www.facebook.com/DeskCamera"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  twitter = "https://twitter.com/DeskCamera"
  reddit = "username"
  linkedin = "https://www.linkedin.com/company/deskcamera"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "https://www.youtube.com/channel/UCYssNv4bAAGV599DHDlYtkw" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "username"
  500px = "username"
  codepen = "username"
  mastodon = "url"
  kaggle = "username"
  weibo = "username"
  slack = "username"
  medium = "username"
  discord = "invite code (https://discord.gg/XXXXXXX)"
  strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "industries"
    name = "Industries"
    weight = 2
    
[[menu.main]]
    parent = "industries"
    name = "Retail & POS Surveillance"
    url = "post/retail"
    weight = 1

[[menu.main]]
    parent = "industries"
    name = "CNI & Manufacturing"
    url = "post/manufacturing"
    weight = 2

[[menu.main]]
    parent = "industries"
    name = "Airports"
    url = "post/airports"
    weight = 3

[[menu.main]]
    parent = "industries"
    name = "City Surveillance"
    url = "post/city"
    weight = 4

[[menu.main]]
    parent = "industries"
    name = "Casinos"
    url = "post/casinos"
    weight = 5

[[menu.main]]
    parent = "industries"
    name = "Education & Healthcare"
    url = "post/healthcare"
    weight = 6

[[menu.main]]
    parent = "industries"
    name = "Banking"
    url = "post/banking"
    weight = 7

[[menu.main]]
    parent = "industries"
    name = "Other industries"
    url = "post/other"
    weight = 8

[[menu.main]]
    name = "Try for free"
    url = "https://www.deskcamera.com/free-trial/"
    weight = 3

[[menu.main]]
    name = "Purchase"
    url = "https://www.deskcamera.com/purchase/"
    weight = 4
